### ISSUE TITLE
First Join RTP Save Location

### ISSUE THREAD

**Issue by roracle** [RonanPlugins/BetterRTP#152]
**Plugin Version**:
3.6.10

**Request**:
An option with the "First join RTP" settings that allow us to save the location of that player and reference it with a placeholder, such as `%betterrtp_player_spawn%`. This way using other plugins, we can alias a teleport command with `/spawn` to execute `/tp %player% %betterrtp_player_spawn%` OR a built in command that automatically does just that.

**How/Why**:
To allow servers a way to hedge against griefers in their creative worlds.

**Additional Context**:
No additional context, but I love this plugin :)

**Comment by TechnicallyCoded** [comment]
## Correct way:
Make your plugin use [RTP_TeleportPostEvent](https://github.com/RonanPlugins/BetterRTP/blob/master/src/main/java/me/SuperRonanCraft/BetterRTP/references/customEvents/RTP_TeleportPostEvent.java) and save that location only once. Ignore subsequent RTPs by that player.

## Hacky/incorrect way:
Set the following settings
```yaml
  RtpOnFirstJoin: # Will execute as console to override delays
    Enabled: true # Make the player rtp when joining the server for the first time
    # Doesn't matter for this :: World: world # World to first rtp in
    # Doesn't matter for this :: SetAsRespawn: true # Save this first rtp as players new spawn point
```
Now use the player join event on priority MONITOR and get the player's location. Save it.
