### ISSUE TITLE
Make delay work also when using /rtp player

### ISSUE THREAD

**Issue by oskarkk** [RonanPlugins/BetterRTP#94]
**Plugin Version**:
Version #3.3.0

**Request**:
Make delay work also when using `/rtp player <player>`.

**How/Why**:
It would be nice, because you can use console command like that for automation, like teleporting after some action from another plugin, and it's better when there's a delay before teleporting. There could be a separate option for this, like:

```
  Delay:
    Enabled: true
    EnabledInConsole: true
    Time: 5
    CancelOnMove: false
```

Or maybe "EnabledWhenTeleportingOthers" but that's kinda long.
